[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.pytest.ini_options]
minversion = '6.0'
addopts = '-ra -q --cov=hello_world'
testpaths = ['tests']

[tool.coverage.run]
branch = true
source = ['hello_world']

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'def __repr__',
    'if self\.debug',
    'raise NotImplementedError',
    'if __name__ == .__main__.:',
    'pass',
    'raise ImportError'
]
ignore_errors = true
omit = ['tests/*', 'setup.py']